- name: Append line to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: 'localhost:/{{ item.name }} /mnt/{{ item.name }} glusterfs defaults,_netdev,backupvolfile-server=localhost 0 0'
    create: yes
  loop: "{{ gluster_volumes }}"

- name: Create systemd mount unit file for GlusterFS
  ansible.builtin.copy:
    dest: "/etc/systemd/system/mnt-{{ item.name }}.mount"
    content: |
      [Unit]
      Description=Mount GlusterFS Volume
      After=glusterfs-server.service
      Requires=glusterfs-server.service

      [Mount]
      What=localhost:/{{ item.name }}
      Where=/mnt/{{ item.name }}
      Type=glusterfs
      Options=_netdev

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  loop: "{{ gluster_volumes }}"

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start GlusterFS volumes
  command: gluster volume start {{ item.name }}
  with_items: "{{ gluster_volumes }}"
  run_once: true

- name: Mount GlusterFS volume
  command: mount.glusterfs localhost:/{{ item.name }} /mnt/{{ item.name }}
  loop: "{{ gluster_volumes }}"